### ISSUE TITLE
aeson doesn't compile with 8.8.1

### ISSUE THREAD

**Issue by GeorgeCo** [bos/aeson#725]
```
bash-3.2$ ghc --version
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.1
 cabal install aeson
...

Resolving dependencies...
Starting     aeson-1.2.1.0
Building     aeson-1.2.1.0
Failed to install aeson-1.2.1.0
Build log ( /Users/gcolpitts/.cabal/logs/ghc-8.8.1/aeson-1.2.1.0-7fzstEpaAzp4aNLGplKATO.log ):
cabal: Entering directory '/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-77369/aeson-1.2.1.0'
Configuring aeson-1.2.1.0...
Preprocessing library for aeson-1.2.1.0..
Building library for aeson-1.2.1.0..
[ 1 of 23] Compiling Data.Aeson.Internal.Functions ( Data/Aeson/Internal/Functions.hs, dist/build/Data/Aeson/Internal/Functions.o )
[ 2 of 23] Compiling Data.Aeson.Parser.UnescapePure ( pure/Data/Aeson/Parser/UnescapePure.hs, dist/build/Data/Aeson/Parser/UnescapePure.o )
[ 3 of 23] Compiling Data.Aeson.Parser.Unescape ( Data/Aeson/Parser/Unescape.hs, dist/build/Data/Aeson/Parser/Unescape.o )
[ 4 of 23] Compiling Data.Aeson.Types.Generic ( Data/Aeson/Types/Generic.hs, dist/build/Data/Aeson/Types/Generic.o )
[ 5 of 23] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, dist/build/Data/Aeson/Types/Internal.o )

Data/Aeson/Types/Internal.hs:160:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
160 |     fail = Fail.fail
    |     ^^^^

Data/Aeson/Types/Internal.hs:161:16: error:
    The INLINE pragma for ‘fail’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘fail’ is declared)
    |
161 |     {-# INLINE fail #-}
    |                ^^^^

Data/Aeson/Types/Internal.hs:175:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
175 |     fail = Fail.fail
    |     ^^^^

Data/Aeson/Types/Internal.hs:176:16: error:
    The INLINE pragma for ‘fail’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘fail’ is declared)
    |
176 |     {-# INLINE fail #-}
    |                ^^^^

Data/Aeson/Types/Internal.hs:288:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
288 |     fail = Fail.fail
    |     ^^^^

Data/Aeson/Types/Internal.hs:289:16: error:
    The INLINE pragma for ‘fail’ lacks an accompanying binding
      (The INLINE pragma must be given where ‘fail’ is declared)
    |
289 |     {-# INLINE fail #-}
    |                ^^^^
cabal: Leaving directory '/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-77369/aeson-1.2.1.0'
cabal: Error: some packages failed to install:
aeson-1.2.1.0-7fzstEpaAzp4aNLGplKATO failed during the building phase. The
exception was:
ExitFailure 1

```

**Comment by bergmark** [comment]
It looks like you are using an old release of aeson, please try 1.4.4.0.

**Comment by GeorgeCo** [comment]
Sorry, not sure how that happened, latest version works fine. I think I may have tried to install another package with --allow-new and it used the old version of aeson.
