### ISSUE TITLE
Not in scope: type constructor or class ‘Applicative’

### ISSUE THREAD

**Issue by joshbohde** [bos/aeson#277]
When compiling `master`, with ghc 7.8.4, `Data.Aeson.Types.Internal` fails to compile with the following error:

    Data/Aeson/Types/Internal.hs:142:10:
        Not in scope: type constructor or class ‘Applicative’
    
    Data/Aeson/Types/Internal.hs:148:10:
        Not in scope: type constructor or class ‘Applicative’
    
    Data/Aeson/Types/Internal.hs:248:10:
        Not in scope: type constructor or class ‘Applicative’

This failure was introduced in commit 1c25679039513c3ff069fe1afd5b5ee99a967378

**Comment by bos** [comment]
Seems to be fixed. Thanks for the report.
